<?php
namespace Fructify\Reload\Tests\Response;

use Fructify\Reload\Response\ResponseWebSocket;

/**
 * Test class for Request.
 * Generated by PHPUnit on 2013-05-30 at 13:37:50.
 */
class ResponseWebSocketTest extends \PHPUnit\Framework\TestCase
{

    public function test__construct()
    {
        $response = new ResponseWebSocket();
        $this->assertEquals(101, $response->getStatusCode());
        $this->assertEquals('Upgrade', $response->headers->get('Connection'));
        $this->assertEquals('websocket', $response->headers->get('Upgrade'));
    }

}
