<?php
namespace Fructify\Reload\Tests\Response;

use Fructify\Reload\Protocol\WebSocket\Frame;
use Fructify\Reload\Response\ResponseWebSocketFrame;

/**
 * Test class for Request.
 * Generated by PHPUnit on 2013-05-30 at 13:37:50.
 */
class ResponseWebSocketFrameTest extends \PHPUnit\Framework\TestCase
{

    public function test__to_string()
    {
        $frame = Frame::generate(md5(microtime().rand()));
        $response = new ResponseWebSocketFrame($frame);
        $this->assertEquals($frame->encode(), (string) $response);
    }

}